server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enableSelfPreservation: false
    wait-time-in-ms-when-sync-empty: 0